### ISSUE TITLE
Custom importers still work?

### ISSUE THREAD

**Issue by IngwiePhoenix** [davidkpiano/sassport#6]
Within my current setup, I am using a custom importer. Well, a 3rd-party module of mine is, at least.

Are these still supported?

**Comment by davidkpiano** [comment]
They will be supported - it's definitely on the roadmap and I plan to tackle that this weekend.

**Comment by IngwiePhoenix** [comment]
Good! Because WebPack has its own importer that can be used to resolve to other stuff - like images and the like. I was going to fork the sass-loader and extend it to use sassport instead. :)

**Comment by davidkpiano** [comment]
@IngwiePhoenix Turns out, this was a pretty trivial change. Check it out:

This commit adds support for custom importers to _override_ Sassport's default importer: https://github.com/davidkpiano/sassport/commit/6a9dde9a90601037fdb5445dedb6ab7a69de54d1

And here's the accompanying unit test: https://github.com/davidkpiano/sassport/blob/master/test/importer.js

With this change, Sassport should be completely interoperable with the Sass Eyeglass custom importer, as well as WebPack's custom importer in sass-loader.

/+ @chriseppstein - you might be interested in this.
