### ISSUE TITLE
instructions for using sassport with gulp-sass, etc

### ISSUE THREAD

**Issue by taxilian** [davidkpiano/sassport#9]
It's awesome how easy you've made it to compile sass stuff using sassport... but for those of us who use a tool such as gulp-sass it's entirely opaque how we might use sassport with those tools.  I'm going to dig into the code and see if I can figure it out, but it'd be nice if you had some examples.  I'd consider providing examples for grunt-sass and gulp-sass at the very least.

I attended a talk at node.js interactive on sassport and was excited to try it out -- until I finally found time to play with it and realized that it's going to require digging through internals to make it work with our environment.

**Comment by davidkpiano** [comment]
Hey @taxilian, thanks for your interest and concern! To make it as seamless as possible to work with Gulp, I've updated [gulp-sassport](https://github.com/davidkpiano/gulp-sassport) in order to take full advantage of [gulp-sass](https://github.com/dlmanning/gulp-sass) without removing functionality from Sassport.

I've also updated the documentation for Gulp-Sassport. Check it out! https://github.com/davidkpiano/gulp-sassport

Please let me know if the documentation makes sense and everything is clear. I'm going to be working on bigger docs and tutorials for Sassport; those will be ready in early 2016.
